services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173" # Map Vite's default port
    volumes:
      # Mount local frontend code into the correct location within the container
      - ./frontend:/app/frontend
      # Use an anonymous volume to persist/hide the node_modules installed during build
      # This prevents the host node_modules (if any) from overwriting the container's
      - /app/frontend/node_modules
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount local code, excluding node_modules for hot-reloading
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      # Override DATABASE_URL to use the docker-compose service name
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/doctor_otter
      - PORT=3000 # Adjust if your backend uses a different port variable
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doctor_otter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
