/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExamenesImport } from './routes/examenes'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ExamenesRoute = ExamenesImport.update({
  id: '/examenes',
  path: '/examenes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/examenes': {
      id: '/examenes'
      path: '/examenes'
      fullPath: '/examenes'
      preLoaderRoute: typeof ExamenesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examenes': typeof ExamenesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examenes': typeof ExamenesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/examenes': typeof ExamenesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examenes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examenes'
  id: '__root__' | '/' | '/examenes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamenesRoute: typeof ExamenesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamenesRoute: ExamenesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/examenes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/examenes": {
      "filePath": "examenes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
